# Generated by Django 5.0.7 on 2024-07-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='posts/images/')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'posts_create',
            },
        ),
        migrations.CreateModel(
            name='ViewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='posts/images/')),
                ('description', models.TextField()),
                ('like', models.BooleanField(default=False)),
                ('view', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'posts_view',
            },
        ),
    ]
