# Generated by Django 5.0.7 on 2024-08-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='created_by',
            field=models.CharField(max_length=200),
        ),
    ]
