# Generated by Django 5.0.7 on 2024-07-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_categories_createpost_category_viewpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='created_by',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewpost',
            name='created_by',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
