# Generated by Django 5.0.7 on 2024-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_createpost_created_by_viewpost_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
