# Generated by Django 5.0.7 on 2024-07-12 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_viewpost_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createpost',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
