# Generated by Django 5.0.7 on 2024-07-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_createpost_created_at_alter_createpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createpost',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createpost',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
