# Generated by Django 5.0.7 on 2024-08-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_comment_post_comment_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='createpost',
            name='create_post_comments',
            field=models.ManyToManyField(related_name='create_posts', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='viewpost',
            name='view_post_comments',
            field=models.ManyToManyField(related_name='view_posts', to='posts.comment'),
        ),
    ]
