# Generated by Django 5.0.7 on 2024-07-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
