# Generated by Django 5.0.7 on 2024-07-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
