# Generated by Django 5.0.7 on 2024-07-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
