# Generated by Django 5.0.7 on 2024-07-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('posts', '0016_delete_login_delete_signup_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='posts_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN')], default='USER', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_name='posts_user_permissions', to='auth.permission'),
        ),
    ]
